name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: "ci"

jobs:
  format-and-lint:
    name: Format and lint, check satellite list
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "scripts/.python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6

      - name: Check
        run: uv run ruff check

      - name: Format
        run: uv run ruff format --check

      - name: Validate satellite constellations
        run: uv run python validate_satellites.py
